---
collections:
  - name: ansible.netcommon
  - name: community.network
  - name: cisco.ios
  - name: cisco.iosxr
  - name: junipernetworks.junos
  - name: arista.eos
  - name: ntc-templates
  # add any other collections your playbooks use
